### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-minify-classnames#10]
@simonlc Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by simonlc** [comment]
Hi, that sounds great, I've made a PR in the posthtml/posthtml repo, the other already included this plugin. I've also invited you to the repo as a collaborator. Thanks! :)

**Comment by Scrum** [comment]
Hi, unfortunately the rights of the co-author are not enough to drag this into the organization, for this I need rights owners to have access to `settings`

**Comment by Scrum** [comment]
@simonlc ping

**Comment by simonlc** [comment]
Okay I transferred the repo towards you. Let me know the next steps.

**Comment by Scrum** [comment]
All is ready. Check your rights to this repository, to improve support, you can add me as a co-author in `npm` to post changes

**Comment by simonlc** [comment]
Done. Thanks for reaching out :)

**Comment by Scrum** [comment]
thank you for your trust
