### ISSUE TITLE
is it possible to use this with webpack?

### ISSUE THREAD

**Issue by vesper8** [posthtml/posthtml-minify-classnames#16]
the example you give does not seem to be compatible with a bundler such as Webpack, wonder if you or anyone knows how to process the html/css output of a Webpack flow

**Comment by Scrum** [comment]
What example are you talking about?

So far I don’t see the connection of `posthtml plugins` with `webpack` or maybe `webpack plugins`

**Comment by vesper8** [comment]
I meant that in your example you show how you can pass a string to your library and it the outputs obfuscated/minified results. But when using Webpack you do not know ahead of time which files will need to be run through since they are generated dynamically and with unique hashes. So instead libraries that are developed with Webpack in mind will be able to pipe the output through their plugins as part of the flow. I hope that makes sense.

In any case I found such a webpack plugin that does what I was looking for here: https://github.com/sndyuk/mangle-css-class-webpack-plugin
