### ISSUE TITLE
Note about emoji

### ISSUE THREAD

**Issue by polarathene** [posthtml/posthtml-minify-classnames#21]
You may want to add a note about the emoji "feature". Each example given uses emoji that are 3-4 bytes each, although some emoji can use well over 20 bytes for a single glyph.

That's "minified" values that are 10-12 bytes (varies in your example ones). The smallest one at 10 bytes (`⏲📂⚗`) is equivalent to `abcdefghij`, thus probably not an actual savings depending on input. If only using `a-z,A-Z` for a total of 52 symbols, and a length of 3 you'd have over 140k permutations (`52^3 = 140,608`), thus the value of emoji providing any value for minification here is low.

**Comment by Scrum** [comment]
@polarathene Hi, that sounds good. Feel free to create PR
