### ISSUE TITLE
Filter option not usable with posthtml-cli

### ISSUE THREAD

**Issue by frankspin89** [posthtml/posthtml-minify-classnames#30]
When using this plugin in combination with posthtml-cli the filter option is not usable because it throws a Type Error: 

`TypeError: this.filter.test is not a function at MinifyClassnames.isClassFiltered` 

**posthtml-cli config.js**

```
{
  "root": "public",
  "input": "**/*.html",
  "output": "dist",

  "options": {
    "sync": false
  },
  "plugins": {
    "posthtml-inline-assets": {
      "transforms": {
        "script" : false
      }
    },
    "posthtml-minify-classnames": {
      "genNameId" : false,
      "filter": "/^.js-/"
    },
    "htmlnano" : {

    }
  }
}

```

**Comment by Scrum** [comment]
@frankspin89 Thank you for letting me know, I will try to sort it out as soon as possible.

If you have a solution, feel free to deal with PR

**Comment by Scrum** [comment]
> "filter": "/^.js-/" 

Here the regex should not be a string.

this example should work for you

_**posthtml.config.js**_
```js
module.exports =  {
  "root": "public",
  "input": "**/*.html",
  "output": "dist",

  "options": {
    "sync": false
  },
  "plugins": {
    "posthtml-inline-assets": {
      "transforms": {
        "script" : false
      }
    },
    "posthtml-minify-classnames": {
      "genNameId" : false,
      "filter": /^.js-/
    },
    "htmlnano" : {

    }
  }
}
```

**Comment by frankspin89** [comment]
Running the code as above is resulting in the following JSON Errors

`ErrorEXError [JSONError]: JSON Error in C:\dev\products\aircontrol\themes\aircontrol\config.json:

  14 |     "posthtml-minify-classnames": {
  15 |       "genNameId" : false,
> 16 |       "filter": /^.js-/
     |                 ^
  17 |     },
  18 |
  19 |     "htmlnano" : {

Unexpected token "/" (0x2F) in JSON at position 283 while parsing near "...e,\r\n      \"filter\": /^.js-/\r\n    },\r\n  \r..."    

  14 |     "posthtml-minify-classnames": {
  15 |       "genNameId" : false,
> 16 |       "filter": /^.js-/
     |                 ^
  17 |     },`

**Comment by Scrum** [comment]
_posthtml.config.**js**_

**Comment by frankspin89** [comment]
Sorry, completely missed that. It's now working perfect! 

Thanks!
