### ISSUE TITLE
Deletes all class names inside HTML files.

### ISSUE THREAD

**Issue by semdzh** [posthtml/posthtml-minify-classnames#34]
When you run the command, the plugin reduces the name of the classes in the css file, and in the html files all the classes are removed. Why does this happen?

And also, for some reason css styles are added to html file in output, but css file should be in assets folder.

This is my posthtml.config.js code:
```
module.exports =  {
  "root": "public",
  "input": "**/*.html",
  "output": "dist",

  "options": {
    "sync": false,
  },
  "plugins": {
    "posthtml-inline-assets": {
      "transforms": {
        "script" : false
      }
    },
    "posthtml-minify-classnames": {
      "genNameId" : false,
      "genNameClass": 'genName',
      "filter": /^.js-/
    }
  }
}
```

**Comment by semdzh** [comment]
> When you run the command, the plugin reduces the name of the classes in the css file, and in the html files all the classes are removed. Why does this happen?

This part is solved. I made a mistake because I compiled the obfuscated classes into a new file.

**Comment by semdzh** [comment]
Tested on a template that consists of php files with the same posthtml.config.js. 

The plugin removes all the styles in the php files, removes parent <?php ?>, does not parse css styles from the assets folder without specifying the exactly path and does not reduce the class names in it. 

In the output breaks the whole structure of the template and php files.

**Comment by Scrum** [comment]
> And also, for some reason css styles are added to html file in output, but css file should be in assets folder.

To place resources in a folder, you can use the plugin [posthtml-style-to-file](https://github.com/posthtml/posthtml-style-to-file)

> When you run the command, the plugin reduces the name of the classes in the css file, and in the html files all the classes are removed. Why does this happen?

there is no need to leave them as they add weight to the page, why minify at all?

> In the output breaks the whole structure of the template and php files.

You probably need to use the directives see in https://github.com/posthtml/posthtml#api
