### ISSUE TITLE
Is it possible to minify class names inside <?php ?>?

### ISSUE THREAD

**Issue by semdzh** [posthtml/posthtml-minify-classnames#35]
_For example_ 
from: `<?php echo '<div class="tw-text-gray-500 tw-uppercase"></div>'; ?>` 
to: `<?php echo '<div class="a b"></div>'; ?>`

**Comment by Scrum** [comment]
> _For example_
> from: `<?php echo '<div class="tw-text-gray-500 tw-uppercase"></div>'; ?>`
> to: `<?php echo '<div class="a b"></div>'; ?>`

This requires a `PHP` parser

**Comment by semdzh** [comment]
> > _For example_
> > from: `<?php echo '<div class="tw-text-gray-500 tw-uppercase"></div>'; ?>`
> > to: `<?php echo '<div class="a b"></div>'; ?>`
> 
> This requires a `PHP` parser

Hey, @Scrum 
Is there any ready-made solution that has already been used with posthtml? I would be grateful for a hint.

**Comment by Scrum** [comment]
> Is there any ready-made solution that has already been used with posthtml? I would be grateful for a hint.

I haven't seen this yet, but it's a good idea.

**Comment by Scrum** [comment]
related to https://github.com/posthtml/posthtml-minify-classnames/issues/34
