### ISSUE TITLE
Is it possible to use this plugin with a Javascript framework like Alpinejs or Vue?

### ISSUE THREAD

**Issue by raguila8** [posthtml/posthtml-minify-classnames#36]
For example, AlpineJS allows you to add directives for adding different classes at different stages of a transition:
The following examples use TailwindCSS utility classes.

```
<div x-data="{ open: false }">
    <button @click="open = ! open">Toggle</button>
 
    <div
        x-show="open"
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 transform scale-90"
        x-transition:enter-end="opacity-100 transform scale-100"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 transform scale-100"
        x-transition:leave-end="opacity-0 transform scale-90"
    >Hello 👋</div>
</div>
```

The utility classes are added at different stages of the transition. However, when applying the plugin, these class names have been minified and no longer exist in the styles. Is there a way to apply the minification to the class names in these directives as well?

**Comment by Scrum** [comment]
@raguila8 These are great questions, and it will take me some time to explore these possibilities. It will be a little faster if you have ready-made examples that I can investigate.

**Comment by Scrum** [comment]
@raguila8 Hi, now you just need to add the necessary attributes to participate in the process through the option `customAttributes`

**Comment by raguila8** [comment]
This is awesome! thanks so much for this.
