### ISSUE TITLE
Getting to v1.0.0

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-minify-classnames#55]
Found a use for this plugin so naturally I'd like to bring it up to date and release a stable `1.0.0`.

- [ ] ESM/CJS hybrid
- [ ] require Node.js 18
- [ ] use Vitest and biomejs
- [ ] add [np](https://www.npmjs.com/package/np) for releases

\+ update dependencies, remove bloat packages etc.

I'll work on a PR and update you there 👍

**Comment by Scrum** [comment]
@cossssmin Thanks
